services:
  v_bot:
    build:
      context: .
      args:
        BUILD_ENV: production
    image: v_bot:latest
    container_name: v_bot
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./auth_baileys:/usr/src/app/auth_baileys
      - ./data:/usr/src/app/data
      - ./temp:/usr/src/app/temp
      - ./cookies.txt:/usr/src/app/cookies.txt:ro
      - ./src:/usr/src/app/src
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
