const logger = require('../utils/logger');
const Groq = require('groq-sdk');

class QuoteCommand {
    constructor() {
        this.groq = null;
        // Cek apakah API Key ada di .env dan bukan placeholder
        if (process.env.GROQ_API_KEY &&
            process.env.GROQ_API_KEY !== 'isi_api_key_kamu_di_sini' &&
            process.env.GROQ_API_KEY.trim() !== '') {

            this.groq = new Groq({
                apiKey: process.env.GROQ_API_KEY,
            });
            logger.info('Groq AI initialized for QuoteCommand');
        } else {
            logger.warn('Groq API Key tidak ditemukan di .env atau masih kosong.');
        }
    }

    /**
     * Send AI generated motivational quote
     */
    async sendQuote(msg) {
        try {
            logger.info('Memproses command .quote (Full AI Mode)');

            if (!this.groq) {
                logger.error('Groq AI tidak terkonfigurasi');
                return msg.reply('❌ Ups, fitur motivasi AI belum siap. Pastikan API Key Groq sudah diisi di file .env ya!');
            }

            let quote = '';
            try {
                let prompt = "Berikan satu kalimat motivasi singkat, keren, dan powerfull dalam bahasa Indonesia. Jangan pakai tanda kutip. Harus bervariasi setiap kali diminta.";

                if (msg.hasQuotedMsg) {
                    const quotedMsg = await msg.getQuotedMessage();
                    prompt = `Seseorang baru saja mengirim pesan ini: "${quotedMsg.body}". \n\nBerikan satu kalimat motivasi atau kata-kata penyemangat yang sangat relevan dan sedikit lucu/asik untuk membalas pesan tersebut dalam bahasa Indonesia. Singkat saja, maksimal 2 kalimat. Jangan pakai tanda kutip.`;
                }

                const chatCompletion = await this.groq.chat.completions.create({
                    messages: [{ role: 'user', content: prompt }],
                    model: 'llama-3.3-70b-versatile',
                });

                quote = chatCompletion.choices[0].message.content.trim();
                logger.success('Motivational quote generated by Groq AI');
            } catch (aiError) {
                logger.error('Error calling Groq API:', aiError.message);
                return msg.reply('❌ Gagal menghubungi AI. Mungkin API Key salah atau kuota habis? Coba cek lagi nanti ya.');
            }

            // Check if it's a reply to a message
            if (msg.hasQuotedMsg) {
                logger.info('Membalas pesan yang di-quote dengan motivasi AI');
                await msg.reply(`"${quote}"\n\n_Semangat terus ya!_ 😘`);
            } else {
                logger.info('Mengirim motivasi AI');
                await msg.reply(`"${quote}"\n\n_Jangan lupa tersenyum!_ 😊 😘`);
            }

            logger.success('AI Motivational quote sent successfully');
        } catch (error) {
            logger.error('Error in QuoteCommand:', error.message);
            throw error;
        }
    }
}

module.exports = new QuoteCommand();
